INSERT ALL
    INTO RGB.DEP (DEP_NO, EMP_NO, DEP_NAME, DEP_STATE) VALUES ('D001', '220001', '인사팀', 'Y')
    INTO RGB.DEP (DEP_NO, EMP_NO, DEP_NAME, DEP_STATE) VALUES ('D002', '220002', '개발팀', 'Y')
    INTO RGB.DEP (DEP_NO, EMP_NO, DEP_NAME, DEP_STATE) VALUES ('D003', '220003', '마케팅팀', 'Y')
    INTO RGB.DEP (DEP_NO, EMP_NO, DEP_NAME, DEP_STATE) VALUES ('D004', '220004', '영업팀', 'Y')
    INTO RGB.DEP (DEP_NO, EMP_NO, DEP_NAME, DEP_STATE) VALUES ('D005', '220005', '재무팀', 'N')
    INTO RGB.DEP (DEP_NO, EMP_NO, DEP_NAME, DEP_STATE) VALUES ('D006', '220006', '인사팀', 'Y')
    INTO RGB.DEP (DEP_NO, EMP_NO, DEP_NAME, DEP_STATE) VALUES ('D007', '220007', '개발팀', 'Y')
    INTO RGB.DEP (DEP_NO, EMP_NO, DEP_NAME, DEP_STATE) VALUES ('D008', '220008', '마케팅팀', 'Y')
    INTO RGB.DEP (DEP_NO, EMP_NO, DEP_NAME, DEP_STATE) VALUES ('D009', '220009', '영업팀', 'Y')
    INTO RGB.DEP (DEP_NO, EMP_NO, DEP_NAME, DEP_STATE) VALUES ('D010', '220010', '재무팀', 'N')
SELECT * FROM dual;

INSERT ALL
    INTO RGB.DEP (DEP_NO, EMP_NO, DEP_NAME, DEP_STATE) VALUES ('D011', '220011', '인사팀', 'Y')
    INTO RGB.DEP (DEP_NO, EMP_NO, DEP_NAME, DEP_STATE) VALUES ('D012', '220012', '개발팀', 'Y')
    INTO RGB.DEP (DEP_NO, EMP_NO, DEP_NAME, DEP_STATE) VALUES ('D013', '220013', '마케팅팀', 'Y')
    INTO RGB.DEP (DEP_NO, EMP_NO, DEP_NAME, DEP_STATE) VALUES ('D014', '220014', '영업팀', 'Y')
    INTO RGB.DEP (DEP_NO, EMP_NO, DEP_NAME, DEP_STATE) VALUES ('D015', '220015', '재무팀', 'N')
    INTO RGB.DEP (DEP_NO, EMP_NO, DEP_NAME, DEP_STATE) VALUES ('D016', '220016', '인사팀', 'Y')
    INTO RGB.DEP (DEP_NO, EMP_NO, DEP_NAME, DEP_STATE) VALUES ('D017', '220017', '개발팀', 'Y')
    INTO RGB.DEP (DEP_NO, EMP_NO, DEP_NAME, DEP_STATE) VALUES ('D018', '220018', '마케팅팀', 'Y')
    INTO RGB.DEP (DEP_NO, EMP_NO, DEP_NAME, DEP_STATE) VALUES ('D019', '220019', '영업팀', 'Y')
    INTO RGB.DEP (DEP_NO, EMP_NO, DEP_NAME, DEP_STATE) VALUES ('D020', '220020', '재무팀', 'N')
SELECT * FROM dual;
