CREATE TABLE EMP (
    EMP_NO VARCHAR2(30) NOT NULL,
    EMP_PASSWORD VARCHAR2(30) NOT NULL,
    EMP_PHONE VARCHAR2(30),
    EMP_NAME VARCHAR2(30) NOT NULL,
    EMP_EMAIL VARCHAR2(50),
    EMP_GENDER CHAR(10) NOT NULL,
    EMP_IDNUM CHAR(14) NOT NULL,
    EMP_JOINDATE DATE NOT NULL,
    EMP_OUTDATE DATE,
    EMP_PHOTO CLOB,
    EMP_STATE CHAR(1) NOT NULL,
    EMP_FULLOFF INTEGER,
    EMP_RESTOFF INTEGER,
    EMP_USEOFF INTEGER,
    PRIMARY KEY (EMP_NO)
);

-- Insert into EMP table
INSERT ALL
    INTO RGB.EMP
        (EMP_NO, EMP_PASSWORD, EMP_PHONE, EMP_NAME, EMP_EMAIL, EMP_GENDER, EMP_IDNUM, EMP_JOINDATE, EMP_STATE, EMP_FULLOFF, EMP_RESTOFF, EMP_USEOFF)
    VALUES
        ('000000', '0000', '010-1111-1111', '테스트', 'test@gmail.com', '남자', '991122-1', TO_DATE('2020-01-01', 'YYYY-MM-DD'), 'Y', NULL, NULL, NULL)
    INTO RGB.EMP
        (EMP_NO, EMP_PASSWORD, EMP_PHONE, EMP_NAME, EMP_EMAIL, EMP_GENDER, EMP_IDNUM, EMP_JOINDATE, EMP_STATE, EMP_FULLOFF, EMP_RESTOFF, EMP_USEOFF)
    VALUES
        ('111111', '0000', '010-1111-1111', '관리자', 'admin@gmail.com', '남자', '991122-1', TO_DATE('2020-01-01', 'YYYY-MM-DD'), 'Y', NULL, NULL, NULL)
SELECT * FROM dual;

INSERT INTO RGB.TEMPLATE
(TEMP_ID, DOC_NO, CTGR_ID, TEMP_TITLE, TEMP_CONTENT, TEMP_REGDATE, TEMP_EDITDATE)
VALUES (
    '111', 
    '1111', 
    '1111', 
    1, 
    '<html><p style="border:1px solid black;">안녕하세요 ㅋㅋㅋㅋ</p></html>',
    SYSTIMESTAMP, -- 등록 날짜
    SYSTIMESTAMP  -- 수정 날짜
);

DELETE FROM RGB.TEMPLATE
WHERE TEMP_ID='111';

SELECT TEMP_ID, DOC_NO, CTGR_ID, TEMP_TITLE, TEMP_CONTENT, TEMP_REGDATE, TEMP_EDITDATE
	FROM TEMPLATE t;