-- EMP 테이블 생성 4번
CREATE TABLE EMP (
    EMP_NO VARCHAR2(30) NOT NULL,
    EMP_PASSWORD VARCHAR2(30) NOT NULL,
    EMP_PHONE VARCHAR2(30),
    EMP_NAME VARCHAR2(30) NOT NULL,
    EMP_EMAIL VARCHAR2(50),
    EMP_GENDER CHAR(10) NOT NULL,
    EMP_IDNUM CHAR(14) NOT NULL,
    EMP_JOINDATE DATE NOT NULL,
    EMP_OUTDATE DATE,
    EMP_PHOTO CLOB,
    EMP_STATE CHAR(1) NOT NULL,
    EMP_FULLOFF NUMBER,
    EMP_RESTOFF NUMBER,
    EMP_USEOFF NUMBER,
    DEP_NO VARCHAR2(50),
    AUTH_NO VARCHAR2(50),
    TIER_NO VARCHAR2(50),
    PRIMARY KEY (EMP_NO),
    FOREIGN KEY (DEP_NO) REFERENCES DEP(DEP_NO),
    FOREIGN KEY (AUTH_NO) REFERENCES AUTH(AUTH_NO),
    FOREIGN KEY (TIER_NO) REFERENCES TIER(TIER_NO)
);

-- ATTENDANCE 테이블 생성 5번
CREATE TABLE ATTENDANCE (
    ATT_NO VARCHAR2(50) NOT NULL,
    EMP_NO VARCHAR2(30) NOT NULL,
    ATT_INTIME DATE,
    ATT_OUTTIME DATE,
    ATT_WORKTIME NUMBER,
    ATT_BASETIME NUMBER,
    PRIMARY KEY (ATT_NO),
    FOREIGN KEY (EMP_NO) REFERENCES EMP(EMP_NO)
);
 
-- DEP 테이블 생성 3번
CREATE TABLE DEP (
    DEP_NO VARCHAR2(50) NOT NULL,
    DEP_NAME VARCHAR2(50) NOT NULL,
    DEP_STATE VARCHAR2(10) NOT NULL,
    PRIMARY KEY (DEP_NO)
);

-- AUTH 테이블 생성 2번
CREATE TABLE AUTH (
    AUTH_NO VARCHAR2(50) NOT NULL,
    AUTH_NAME VARCHAR2(50) NOT NULL,
    PRIMARY KEY (AUTH_NO)
);

-- TIER 테이블 생성 1번
CREATE TABLE TIER (
    TIER_NO VARCHAR2(50) NOT NULL,
    TIER_NAME VARCHAR2(50) NOT NULL,
    PRIMARY KEY (TIER_NO)
);
