CREATE TABLE EMP (
    EMP_NO VARCHAR2(30) NOT NULL,
    EMP_PASSWORD VARCHAR2(30) NOT NULL,
    EMP_PHONE VARCHAR2(30),
    EMP_NAME VARCHAR2(30) NOT NULL,
    EMP_EMAIL VARCHAR2(50),
    EMP_GENDER CHAR(10) NOT NULL,
    EMP_IDNUM CHAR(14) NOT NULL,
    EMP_JOINDATE DATE NOT NULL,
    EMP_OUTDATE DATE,
    EMP_PHOTO CLOB,
    EMP_STATE CHAR(1) NOT NULL,
    EMP_FULLOFF INTEGER,
    EMP_RESTOFF INTEGER,
    EMP_USEOFF INTEGER,
    PRIMARY KEY (EMP_NO)
);

CREATE TABLE DEP (
    DEP_NO VARCHAR2(50) NOT NULL,
    EMP_NO VARCHAR2(30) NOT NULL,
    DEP_NAME VARCHAR2(50) NOT NULL,
    DEP_STATE VARCHAR2(10) NOT NULL,
    PRIMARY KEY (DEP_NO),
    FOREIGN KEY (EMP_NO) REFERENCES EMP(EMP_NO)
);

CREATE TABLE AUTH (
    AUTH_NO VARCHAR2(50) NOT NULL,
    EMP_NO VARCHAR2(30) NOT NULL,
    AUTH_NAME VARCHAR2(50) NOT NULL,
    PRIMARY KEY (AUTH_NO),
    FOREIGN KEY (EMP_NO) REFERENCES EMP(EMP_NO)
);

CREATE TABLE TIER (
    TIER_NO VARCHAR2(50) NOT NULL,
    EMP_NO VARCHAR2(30) NOT NULL,
    TIER_NAME VARCHAR2(50) NOT NULL,
    PRIMARY KEY (TIER_NO),
    FOREIGN KEY (EMP_NO) REFERENCES EMP(EMP_NO)
);

CREATE TABLE ATTENDANCE (
    ATT_NO VARCHAR2(50) NOT NULL,
    EMP_NO VARCHAR2(30) NOT NULL,
    ATT_INTIME DATE,
    ATT_OUTTIME DATE,
    ATT_WORKTIME INTEGER,
    ATT_BASETIME INTEGER,
    PRIMARY KEY (ATT_NO),
    FOREIGN KEY (EMP_NO) REFERENCES EMP(EMP_NO)
);




