-- ATTENDANCE 테이블 생성
CREATE TABLE ATTENDANCE (
    EMP_NO VARCHAR2(30) NOT NULL,
    ATT_INTIME DATE,
    ATT_OUTTIME DATE,
    ATT_WORKTIME NUMBER,
    ATT_BASETIME NUMBER,
    ATT_LATE NUMBER,
    ATT_STATUS VARCHAR2(30),
    FOREIGN KEY (EMP_NO) REFERENCES EMP(EMP_NO)
);


-- 8월과 9월의 날짜를 생성하고 ATTENDANCE 테이블에 데이터 삽입
INSERT INTO ATTENDANCE (
    EMP_NO, ATT_INTIME, ATT_OUTTIME, ATT_WORKTIME, ATT_BASETIME, ATT_LATE, ATT_STATUS
)
SELECT 
    '999999' AS EMP_NO,
    (TO_DATE('2024-08-01', 'YYYY-MM-DD') + (LEVEL - 1)) + INTERVAL '09:00:00' HOUR TO SECOND AS ATT_INTIME, -- 출근 시간
    (TO_DATE('2024-08-01', 'YYYY-MM-DD') + (LEVEL - 1)) + INTERVAL '17:00:00' HOUR TO SECOND AS ATT_OUTTIME, -- 퇴근 시간
    480 AS ATT_WORKTIME, -- 8시간 근무 (480분)
    480 AS ATT_BASETIME, -- 기준 시간과 동일
    0 AS ATT_LATE, -- 지각 없음
    '정상' AS ATT_STATUS -- 상태는 '정상'
FROM DUAL
CONNECT BY LEVEL <= (TO_DATE('2024-09-30', 'YYYY-MM-DD') - TO_DATE('2024-08-01', 'YYYY-MM-DD') + 1)
AND TO_CHAR(TO_DATE('2024-08-01', 'YYYY-MM-DD') + (LEVEL - 1), 'DY', 'NLS_DATE_LANGUAGE=KOREAN') NOT IN ('SAT', 'SUN');