
	UPDATE ANSWERBOARD SET DELFLAG ='Y'
		WHERE DELFLAG ='N'
		AND 

UPDATE TEMPLATE SET TEMP_TITLE = 'ㅎㅇㅎㅇ', TEMP_CONTENT = 'ㅎㅇㅎㅇ'
WHERE TEMP_ID = '1'

SELECT DOC_NO, DOC_NAME, EMP_NAME, TO_CHAR(DOC_EXP, 'YYYY.MM.DD') DOC_EXP
FROM DOCUMENT d JOIN EMP e
USING (EMP_NO);

SELECT DOC_NO, DOC_NAME, EMP_NAME, TO_CHAR(DOC_EXP, 'YYYY.MM.DD') DOC_EXP
FROM DOCUMENT d, EMP e, TEMPLATE t 
WHERE d.EMP_NO = e.EMP_NO 
AND d.TEMP_ID = t.TEMP_ID;
	
SELECT APP_PROCEDURE
FROM APPROVER a 
WHERE DOC_NO = 'D037';